name: weixin
on:
  workflow_dispatch:
  schedule: 
    # UTC 时间 23 点，北京时间上午 7 点运行
    - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set timezone
        run: echo "TZ=Asia/Shanghai" >> $GITHUB_ENV

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run weixin script
        run: python3 main.py
        env:
          TZ: Asia/Shanghai
